import type { Post } from "../../components/posts/postTypes.ts";

function pendingPost(
	id: number,
	title: string,
	content: string,
	firstName: string,
	lastName: string,
	departmentName: string,
	postTag: string,
	hoursAgo: number,
	extra: Partial<Post> = {},
): Post {
	return {
		id,
		title,
		content,
		firstName,
		lastName,
		departmentName,
		postTag,
		status: "PENDING_APPROVAL",
		createdAt: new Date(Date.now() - hoursAgo * 3600000).toISOString(),
		upvoteCount: 0,
		downvoteCount: 0,
		...extra,
	};
}

export const mockPosts: Post[] = [
	{
		id: 2,
		title: "docker containers are basically just chroot with marketing",
		content:
			"Everyone acts like Docker is revolutionary but it's literally just chroot on steroids. The real innovation is the ecosystem and tooling, not the technology itself.",
		firstName: "Jane",
		lastName: "Smith",
		departmentName: "DCISM",
		postTag: "Software Engineering",
		status: "PENDING_APPROVAL",
		createdAt: new Date(Date.now() - 5 * 3600000).toISOString(),
		upvoteCount: 15,
		downvoteCount: 8,
	},
	{
		id: 6,
		title: "How I built a real-time chat app with WebSockets",
		content:
			"Step by step guide to building a real-time chat application using Node.js and WebSockets. Includes handling reconnections, message queuing, and room management.",
		firstName: "Maria",
		lastName: "Santos",
		departmentName: "DCISM",
		postTag: "Web Development",
		status: "PENDING_APPROVAL",
		createdAt: new Date(Date.now() - 3 * 3600000).toISOString(),
		upvoteCount: 7,
		downvoteCount: 1,
		hasGithub: true,
	},
	{
		id: 8,
		title: "Linux terminal commands cheat sheet for CS students",
		content:
			"A comprehensive cheat sheet covering file operations, process management, networking, and text processing commands you'll actually use in your courses.",
		firstName: "Lisa",
		lastName: "Tan",
		departmentName: "DCISM",
		postTag: "Operating Systems",
		status: "PENDING_APPROVAL",
		createdAt: new Date(Date.now() - 8 * 3600000).toISOString(),
		upvoteCount: 12,
		downvoteCount: 0,
	},
	pendingPost(
		11,
		"Debugging memory leaks in long-running Node services",
		"A field guide to recognizing heap growth, capturing comparable snapshots, and tracing retained objects back to application code.",
		"Kevin",
		"Lorenzo",
		"DCISM",
		"Web Development",
		10,
		{ upvoteCount: 9, downvoteCount: 1 },
	),
	pendingPost(
		14,
		"A worked example of Dijkstra's shortest-path algorithm",
		"This example builds the priority queue one step at a time and reconstructs the final route from predecessor links.",
		"Angela",
		"Marquez",
		"DCISM",
		"Algorithms and Complexities",
		12,
		{ upvoteCount: 14, attachmentCount: 1 },
	),
	pendingPost(
		17,
		"What I learned from migrating a project to TypeScript",
		"Notes on introducing strict types incrementally, handling third-party libraries, and choosing migration boundaries that keep the application deployable.",
		"Victor",
		"Neri",
		"Engineering",
		"Software Engineering",
		15,
		{ upvoteCount: 6, hasGithub: true },
	),
	pendingPost(
		20,
		"Understanding subnet masks with practical examples",
		"A set of worked IPv4 subnetting examples covering network ranges, usable addresses, broadcast addresses, and CIDR notation.",
		"Grace",
		"Molina",
		"DCISM",
		"Computer Networks",
		18,
		{ upvoteCount: 11 },
	),
	pendingPost(
		23,
		"Safer ways to handle secrets in local development",
		"A comparison of environment files, secret managers, development credentials, and repository checks that prevent accidental exposure.",
		"Nathan",
		"Evangelista",
		"DCISM",
		"Cybersecurity",
		21,
		{ upvoteCount: 8, downvoteCount: 1, hasLink: true },
	),
	pendingPost(
		26,
		"Notes from building an offline-first study planner",
		"An account of caching schedules locally, resolving edits after reconnecting, and communicating synchronization state to users.",
		"Clarisse",
		"Dizon",
		"DCISM",
		"Web Development",
		24,
		{ upvoteCount: 13, hasGithub: true },
	),
	pendingPost(
		29,
		"How deadlocks form and how databases detect them",
		"Two transaction timelines illustrate circular waits, lock ordering, timeout strategies, and deadlock victim selection.",
		"Owen",
		"Cabrera",
		"Business",
		"Databases",
		28,
		{ upvoteCount: 10 },
	),
	pendingPost(
		32,
		"A beginner-friendly guide to shell pipelines",
		"Practical examples combine standard input, output redirection, grep, sort, and awk to answer questions from ordinary log files.",
		"Irene",
		"Go",
		"DCISM",
		"Operating Systems",
		31,
		{ upvoteCount: 12, attachmentCount: 1 },
	),
	pendingPost(
		35,
		"Choosing meaningful metrics for an API",
		"A proposal for measuring request volume, latency, failures, and saturation while avoiding dashboards that collect numbers without answering operational questions.",
		"Felix",
		"Antonio",
		"Engineering",
		"Software Engineering",
		36,
		{ upvoteCount: 7 },
	),
	pendingPost(
		38,
		"Using property-based tests for parsers",
		"A small parser example demonstrates generators, invariants, shrinking, and the kinds of edge cases that example-based tests often miss.",
		"Mae",
		"Robles",
		"DCISM",
		"Developer Tools",
		42,
		{ upvoteCount: 9, hasGithub: true },
	),
	pendingPost(
		41,
		"How browser caching affects front-end deployments",
		"An explanation of cache-control directives, fingerprinted assets, validation requests, and strategies for safely shipping a new application version.",
		"Ronald",
		"Yap",
		"DCISM",
		"Web Development",
		47,
		{ upvoteCount: 16, downvoteCount: 2 },
	),
	pendingPost(
		44,
		"Reading an execution plan for the first time",
		"A guided walkthrough of scans, joins, row estimates, and costs in a database execution plan, followed by a simple indexing exercise.",
		"Elaine",
		"Chua",
		"Business",
		"Databases",
		53,
		{ upvoteCount: 15, attachmentCount: 2 },
	),
	pendingPost(
		47,
		"Implementing a bounded work queue in TypeScript",
		"A concurrency-limited queue processes asynchronous jobs with backpressure, cancellation, and predictable error handling.",
		"Harvey",
		"Pineda",
		"DCISM",
		"Data Structures and Algorithms",
		60,
		{ upvoteCount: 11, hasGithub: true },
	),
	pendingPost(
		50,
		"A practical introduction to digital signatures",
		"The article signs and verifies a document, then explains hashing, key ownership, certificate trust, and common verification failures.",
		"Monica",
		"Lazaro",
		"Arts and Sciences",
		"Cybersecurity",
		67,
		{ upvoteCount: 18, downvoteCount: 1 },
	),
	pendingPost(
		53,
		"Documenting architecture decisions in student teams",
		"A compact decision-record template captures context, alternatives, consequences, and follow-up work without turning documentation into a separate project.",
		"Jerome",
		"Abad",
		"DCISM",
		"Technical Writing",
		74,
		{ upvoteCount: 8, hasLink: true },
	),
];
