import type { Course } from "../../components/tables/coursesTable.ts";
import type { DropdownOption } from "../../components/controls/dropdown.ts";

export const mockCourses: Course[] = [
	{
		id: 1,
		name: "BS Computer Science",
		code: "CS",
		department: "DCISM",
		created: "Sep 1, 2026",
	},
	{
		id: 2,
		name: "BS Information Technology",
		code: "IT",
		department: "DCISM",
		created: "Sep 1, 2026",
	},
	{
		id: 3,
		name: "BS Information Management",
		code: "IM",
		department: "DCISM",
		created: "Sep 2, 2026",
	},
	{
		id: 4,
		name: "BS Data Science",
		code: "DS",
		department: "DCISM",
		created: "Sep 3, 2026",
	},
	{
		id: 5,
		name: "BS Software Engineering",
		code: "SE",
		department: "DCISM",
		created: "Sep 5, 2026",
	},
	{
		id: 6,
		name: "BS Cyber Security",
		code: "CSec",
		department: "DCISM",
		created: "Sep 7, 2026",
	},
	{
		id: 7,
		name: "BS Computer Engineering",
		code: "CE",
		department: "DCISM",
		created: "Sep 8, 2026",
	},
	{
		id: 8,
		name: "BS Multimedia Arts",
		code: "MMA",
		department: "DCISM",
		created: "Sep 10, 2026",
	},
	{
		id: 9,
		name: "BS Entertainment and Multimedia Computing",
		code: "EMC",
		department: "DCISM",
		created: "Sep 12, 2026",
	},
	{
		id: 10,
		name: "BS Web Development",
		code: "WD",
		department: "DCISM",
		created: "Sep 15, 2026",
	},
	{
		id: 11,
		name: "BS Network Engineering",
		code: "NE",
		department: "DCISM",
		created: "Sep 15, 2026",
	},
	{
		id: 12,
		name: "BS Artificial Intelligence",
		code: "AI",
		department: "DCISM",
		created: "Sep 18, 2026",
	},
	{
		id: 13,
		name: "BS Information Systems",
		code: "IS",
		department: "DCISM",
		created: "Sep 19, 2026",
	},
	{
		id: 14,
		name: "BS Computer Technology",
		code: "CT",
		department: "DCISM",
		created: "Sep 19, 2026",
	},
	{
		id: 15,
		name: "BS Business Analytics",
		code: "BA",
		department: "DCISM",
		created: "Sep 20, 2026",
	},
	{
		id: 16,
		name: "BS Applied Computing",
		code: "AC",
		department: "DCISM",
		created: "Sep 20, 2026",
	},
	{
		id: 17,
		name: "MS Computer Science",
		code: "MSCS",
		department: "DCISM",
		created: "Sep 21, 2026",
	},
	{
		id: 18,
		name: "MS Information Technology",
		code: "MSIT",
		department: "DCISM",
		created: "Sep 21, 2026",
	},
	{
		id: 19,
		name: "MS Data Science",
		code: "MSDS",
		department: "DCISM",
		created: "Sep 22, 2026",
	},
	{
		id: 20,
		name: "MS Information Systems",
		code: "MSIS",
		department: "DCISM",
		created: "Sep 22, 2026",
	},
	{
		id: 21,
		name: "Master in Cybersecurity",
		code: "MCYB",
		department: "DCISM",
		created: "Sep 23, 2026",
	},
	{
		id: 22,
		name: "PhD Computer Science",
		code: "PhDCS",
		department: "DCISM",
		created: "Sep 24, 2026",
	},
	{
		id: 23,
		name: "Diploma in Software Development",
		code: "DSD",
		department: "DCISM",
		created: "Sep 25, 2026",
	},
	{
		id: 24,
		name: "Diploma in Data Analytics",
		code: "DDA",
		department: "DCISM",
		created: "Sep 26, 2026",
	},
];

export const departmentOptions: DropdownOption[] = [
	{ value: "DCISM", label: "DCISM" },
];
