import type { DropdownOption } from "../../components/controls/dropdown.ts";
import type { Post } from "../../components/posts/postTypes.ts";

function mockPost(
	id: number,
	title: string,
	content: string,
	firstName: string,
	lastName: string,
	departmentName: string,
	postTag: string,
	hoursAgo: number,
	extra: Partial<Post> = {},
): Post {
	return {
		id,
		title,
		content,
		firstName,
		lastName,
		departmentName,
		postTag,
		status: "APPROVED",
		createdAt: new Date(Date.now() - hoursAgo * 3600000).toISOString(),
		upvoteCount: 0,
		downvoteCount: 0,
		...extra,
	};
}

export const posts: Post[] = [
	mockPost(
		201,
		"A practical guide to profiling Node.js applications",
		"A walkthrough of CPU profiles, heap snapshots, and event-loop monitoring, with a repeatable process for finding performance bottlenecks before optimizing them.",
		"Mia",
		"Reyes",
		"DCISM",
		"Web Development",
		1,
		{ upvoteCount: 24, downvoteCount: 1, hasGithub: true },
	),
	mockPost(
		202,
		"Understanding B-trees through database indexes",
		"This visual explanation connects B-tree operations to the way database indexes reduce disk reads, including examples of search, insertion, and node splitting.",
		"Noah",
		"Santos",
		"DCISM",
		"Algorithms and Complexities",
		2,
		{ upvoteCount: 31, downvoteCount: 2 },
	),
	mockPost(
		203,
		"Building accessible forms without a UI framework",
		"A concise checklist for labels, validation messages, focus management, and keyboard navigation when creating accessible forms with semantic HTML and TypeScript.",
		"Alyssa",
		"Cruz",
		"DCISM",
		"Software Engineering",
		5,
		{ upvoteCount: 18, hasLink: true },
	),
	mockPost(
		204,
		"What virtual memory actually does for a process",
		"An introduction to address spaces, paging, page faults, and memory mapping, focused on the details that help explain common application performance issues.",
		"Ethan",
		"Lim",
		"Engineering",
		"Operating Systems",
		26,
		{ upvoteCount: 42, downvoteCount: 3 },
	),
	mockPost(
		205,
		"Choosing the right data structure for search",
		"A comparison of hash tables, balanced trees, tries, and sorted arrays, with practical tradeoffs for lookup speed, ordered iteration, and memory use.",
		"Sofia",
		"Garcia",
		"DCISM",
		"Data Structures and Algorithms",
		48,
		{ upvoteCount: 37, downvoteCount: 1, attachmentCount: 1 },
	),
	mockPost(
		206,
		"Designing a campus network for reliability",
		"A practical overview of redundant links, routing protocols, monitoring, and failure testing for a small campus network.",
		"Liam",
		"Torres",
		"Engineering",
		"Computer Networks",
		56,
	),
	mockPost(
		207,
		"How to read a research paper efficiently",
		"A repeatable three-pass method for identifying a paper's contribution, evaluating its evidence, and taking useful notes.",
		"Isabella",
		"Flores",
		"Arts and Sciences",
		"Research",
		72,
	),
	mockPost(
		208,
		"CSS layout debugging without guesswork",
		"Use browser layout tools, containing blocks, and a short diagnostic checklist to resolve common flexbox and grid issues.",
		"Lucas",
		"Mendoza",
		"DCISM",
		"Web Development",
		96,
	),
	mockPost(
		209,
		"A gentle introduction to public-key cryptography",
		"An intuitive explanation of key pairs, signatures, and the assumptions that make modern public-key systems useful.",
		"Chloe",
		"Navarro",
		"Arts and Sciences",
		"Cybersecurity",
		120,
	),
	mockPost(
		210,
		"Testing asynchronous TypeScript code",
		"Patterns for deterministic tests around promises, timers, retries, and event-driven code without introducing fragile delays.",
		"Gabriel",
		"Ramos",
		"DCISM",
		"Software Engineering",
		144,
	),
	mockPost(
		211,
		"Practical Git workflows for student teams",
		"A lightweight branch, review, and release workflow that keeps class projects moving while preserving a useful history.",
		"Emma",
		"Aquino",
		"Business",
		"Developer Tools",
		168,
	),
	mockPost(
		212,
		"Visualizing graph traversal algorithms",
		"Step-by-step examples of breadth-first and depth-first traversal, including the role of queues, stacks, and visited sets.",
		"Mateo",
		"Villanueva",
		"DCISM",
		"Algorithms and Complexities",
		192,
	),
	mockPost(
		213,
		"Writing clearer technical documentation",
		"Simple techniques for structuring explanations, choosing examples, and reviewing documentation from a reader's perspective.",
		"Zoe",
		"Castillo",
		"Arts and Sciences",
		"Technical Writing",
		216,
	),
	mockPost(
		214,
		"When to normalize a relational database",
		"Examples that show how normalization prevents update anomalies and when selective denormalization can be worthwhile.",
		"Daniel",
		"Ocampo",
		"Business",
		"Databases",
		240,
	),
];

function makeOptions(values: string[]): DropdownOption[] {
	return [...new Set(values)]
		.sort((a, b) => a.localeCompare(b))
		.map((value) => ({ value, label: value }));
}

export const departmentOptions = makeOptions(
	posts.map((post) => post.departmentName),
);
export const tagOptions = makeOptions(posts.map((post) => post.postTag));
