import type { DropdownOption } from "../../components/controls/dropdown.ts";
import type { Post } from "../../components/posts/postTypes.ts";

function mockPost(
	id: number,
	title: string,
	content: string,
	firstName: string,
	lastName: string,
	departmentName: string,
	postTag: string,
	hoursAgo: number,
	extra: Partial<Post> = {},
): Post {
	return {
		id,
		title,
		content,
		firstName,
		lastName,
		departmentName,
		postTag,
		status: "APPROVED",
		createdAt: new Date(Date.now() - hoursAgo * 3600000).toISOString(),
		upvoteCount: 0,
		downvoteCount: 0,
		...extra,
	};
}

export const posts: Post[] = [
	mockPost(
		201,
		"A practical guide to profiling Node.js applications",
		"A walkthrough of CPU profiles, heap snapshots, and event-loop monitoring, with a repeatable process for finding performance bottlenecks before optimizing them.",
		"Mia",
		"Reyes",
		"DCISM",
		"Web Development",
		1,
		{ upvoteCount: 24, downvoteCount: 1, hasGithub: true },
	),
	mockPost(
		202,
		"Understanding B-trees through database indexes",
		"This visual explanation connects B-tree operations to the way database indexes reduce disk reads, including examples of search, insertion, and node splitting.",
		"Noah",
		"Santos",
		"DCISM",
		"Algorithms and Complexities",
		2,
		{ upvoteCount: 31, downvoteCount: 2 },
	),
	mockPost(
		203,
		"Building accessible forms without a UI framework",
		"A concise checklist for labels, validation messages, focus management, and keyboard navigation when creating accessible forms with semantic HTML and TypeScript.",
		"Alyssa",
		"Cruz",
		"DCISM",
		"Software Engineering",
		5,
		{ upvoteCount: 18, hasLink: true },
	),
	mockPost(
		204,
		"What virtual memory actually does for a process",
		"An introduction to address spaces, paging, page faults, and memory mapping, focused on the details that help explain common application performance issues.",
		"Ethan",
		"Lim",
		"Engineering",
		"Operating Systems",
		26,
		{ upvoteCount: 42, downvoteCount: 3 },
	),
	mockPost(
		205,
		"Choosing the right data structure for search",
		"A comparison of hash tables, balanced trees, tries, and sorted arrays, with practical tradeoffs for lookup speed, ordered iteration, and memory use.",
		"Sofia",
		"Garcia",
		"DCISM",
		"Data Structures and Algorithms",
		48,
		{ upvoteCount: 37, downvoteCount: 1, attachmentCount: 1 },
	),
	mockPost(
		206,
		"Designing a campus network for reliability",
		"A practical overview of redundant links, routing protocols, monitoring, and failure testing for a small campus network.",
		"Liam",
		"Torres",
		"Engineering",
		"Computer Networks",
		56,
	),
	mockPost(
		207,
		"How to read a research paper efficiently",
		"A repeatable three-pass method for identifying a paper's contribution, evaluating its evidence, and taking useful notes.",
		"Isabella",
		"Flores",
		"Arts and Sciences",
		"Research",
		72,
	),
	mockPost(
		208,
		"CSS layout debugging without guesswork",
		"Use browser layout tools, containing blocks, and a short diagnostic checklist to resolve common flexbox and grid issues.",
		"Lucas",
		"Mendoza",
		"DCISM",
		"Web Development",
		96,
	),
	mockPost(
		209,
		"A gentle introduction to public-key cryptography",
		"An intuitive explanation of key pairs, signatures, and the assumptions that make modern public-key systems useful.",
		"Chloe",
		"Navarro",
		"Arts and Sciences",
		"Cybersecurity",
		120,
	),
	mockPost(
		210,
		"Testing asynchronous TypeScript code",
		"Patterns for deterministic tests around promises, timers, retries, and event-driven code without introducing fragile delays.",
		"Gabriel",
		"Ramos",
		"DCISM",
		"Software Engineering",
		144,
	),
	mockPost(
		211,
		"Practical Git workflows for student teams",
		"A lightweight branch, review, and release workflow that keeps class projects moving while preserving a useful history.",
		"Emma",
		"Aquino",
		"Business",
		"Developer Tools",
		168,
	),
	mockPost(
		212,
		"Visualizing graph traversal algorithms",
		"Step-by-step examples of breadth-first and depth-first traversal, including the role of queues, stacks, and visited sets.",
		"Mateo",
		"Villanueva",
		"DCISM",
		"Algorithms and Complexities",
		192,
	),
	mockPost(
		213,
		"Writing clearer technical documentation",
		"Simple techniques for structuring explanations, choosing examples, and reviewing documentation from a reader's perspective.",
		"Zoe",
		"Castillo",
		"Arts and Sciences",
		"Technical Writing",
		216,
	),
	mockPost(
		214,
		"When to normalize a relational database",
		"Examples that show how normalization prevents update anomalies and when selective denormalization can be worthwhile.",
		"Daniel",
		"Ocampo",
		"Business",
		"Databases",
		240,
	),
	mockPost(
		215,
		"A checklist for reviewing REST API designs",
		"A review guide covering resource naming, status codes, pagination, error responses, versioning, and documentation before an API reaches production.",
		"Bianca",
		"Domingo",
		"DCISM",
		"Web Development",
		264,
		{ upvoteCount: 29, downvoteCount: 2, hasLink: true },
	),
	mockPost(
		216,
		"Why database transactions need isolation levels",
		"Concrete examples of dirty reads, nonrepeatable reads, and phantom reads, followed by guidance on choosing an isolation level for an application.",
		"Marco",
		"Del Rosario",
		"DCISM",
		"Databases",
		288,
		{ upvoteCount: 34, downvoteCount: 1 },
	),
	mockPost(
		217,
		"Setting up continuous integration for a class project",
		"A practical pipeline that runs formatting, type checking, tests, and builds on every pull request while keeping feedback quick for contributors.",
		"Nina",
		"Pascual",
		"Engineering",
		"Developer Tools",
		312,
		{ upvoteCount: 21, hasGithub: true },
	),
	mockPost(
		218,
		"How DNS resolves a domain name",
		"A packet-level tour from the browser cache to recursive and authoritative name servers, including TTLs and common sources of resolution failures.",
		"Adrian",
		"Bautista",
		"DCISM",
		"Computer Networks",
		336,
		{ upvoteCount: 40, downvoteCount: 2 },
	),
	mockPost(
		219,
		"Designing useful error messages for web applications",
		"Patterns for writing actionable validation, authentication, and system error messages without exposing sensitive implementation details.",
		"Camille",
		"Valdez",
		"Arts and Sciences",
		"Software Engineering",
		360,
		{ upvoteCount: 17 },
	),
	mockPost(
		220,
		"Comparing process scheduling algorithms",
		"Worked examples of first-come first-served, shortest-job-first, priority, and round-robin scheduling with turnaround and waiting-time calculations.",
		"Rafael",
		"Manalo",
		"DCISM",
		"Operating Systems",
		384,
		{ upvoteCount: 26, attachmentCount: 2 },
	),
	mockPost(
		221,
		"Threat modeling a student web portal",
		"A small STRIDE-based threat model that identifies assets, trust boundaries, likely abuse cases, and practical mitigations for a campus portal.",
		"Julia",
		"Mercado",
		"DCISM",
		"Cybersecurity",
		408,
		{ upvoteCount: 38, downvoteCount: 1 },
	),
	mockPost(
		222,
		"Making sense of algorithmic complexity in practice",
		"Examples showing where asymptotic analysis predicts real performance well and where constants, caching, and input size change the outcome.",
		"Paolo",
		"Soriano",
		"Engineering",
		"Algorithms and Complexities",
		432,
		{ upvoteCount: 33 },
	),
	mockPost(
		223,
		"Planning a reliable database backup strategy",
		"A guide to full and incremental backups, retention schedules, restore drills, encryption, and recovery-point objectives for small systems.",
		"Leah",
		"Fernandez",
		"Business",
		"Databases",
		456,
		{ upvoteCount: 20, hasLink: true },
	),
	mockPost(
		224,
		"State management patterns for small front-end apps",
		"A comparison of local state, lifted state, event-driven stores, and URL state, with examples of when each approach keeps an application simpler.",
		"Andre",
		"Salazar",
		"DCISM",
		"Web Development",
		480,
		{ upvoteCount: 27, downvoteCount: 2, hasGithub: true },
	),
	mockPost(
		225,
		"Writing unit tests that survive refactoring",
		"Techniques for testing observable behavior, choosing stable boundaries, and replacing brittle implementation-focused assertions.",
		"Katrina",
		"Aguilar",
		"DCISM",
		"Software Engineering",
		504,
		{ upvoteCount: 36 },
	),
	mockPost(
		226,
		"An introduction to container orchestration",
		"An overview of scheduling, service discovery, health checks, scaling, and rolling updates using a small multi-service application as the example.",
		"Miguel",
		"David",
		"Engineering",
		"Operating Systems",
		528,
		{ upvoteCount: 30, attachmentCount: 1 },
	),
	mockPost(
		227,
		"Using sequence diagrams to clarify system behavior",
		"A guide to modeling requests, asynchronous events, retries, and failures so a team can validate interactions before implementation.",
		"Therese",
		"Padilla",
		"Arts and Sciences",
		"Technical Writing",
		552,
		{ upvoteCount: 16 },
	),
	mockPost(
		228,
		"Common causes of slow SQL queries",
		"A diagnostic workflow for missing indexes, poor join plans, excessive result sets, lock contention, and stale database statistics.",
		"Joaquin",
		"Rivera",
		"DCISM",
		"Databases",
		576,
		{ upvoteCount: 45, downvoteCount: 3 },
	),
	mockPost(
		229,
		"Building a keyboard-friendly navigation menu",
		"A semantic HTML and TypeScript example that handles focus order, escape behavior, visible focus, and screen-reader announcements.",
		"Patricia",
		"Uy",
		"DCISM",
		"Web Development",
		600,
		{ upvoteCount: 22, hasGithub: true },
	),
	mockPost(
		230,
		"What happens during a TLS handshake",
		"A readable trace of certificate validation, key agreement, cipher negotiation, and session resumption in a modern TLS connection.",
		"Samuel",
		"Co",
		"DCISM",
		"Cybersecurity",
		624,
		{ upvoteCount: 41, downvoteCount: 1 },
	),
	mockPost(
		231,
		"Estimating software tasks with less guesswork",
		"A lightweight approach using task decomposition, uncertainty ranges, reference work, and short feedback cycles instead of single-point estimates.",
		"Denise",
		"Alonzo",
		"Business",
		"Software Engineering",
		648,
		{ upvoteCount: 19 },
	),
	mockPost(
		232,
		"A visual guide to hash table collisions",
		"Diagrams and examples comparing separate chaining, linear probing, and double hashing under different load factors.",
		"Enzo",
		"Martinez",
		"DCISM",
		"Data Structures and Algorithms",
		672,
		{ upvoteCount: 32, attachmentCount: 3 },
	),
];

function makeOptions(values: string[]): DropdownOption[] {
	return [...new Set(values)]
		.sort((a, b) => a.localeCompare(b))
		.map((value) => ({ value, label: value }));
}

export const departmentOptions = makeOptions(
	posts.map((post) => post.departmentName),
);
export const tagOptions = makeOptions(posts.map((post) => post.postTag));
