import type { User } from "../../components/tables/usersTable.ts";

export const mockUsers: User[] = [
	{
		id: 1,
		first_name: "John",
		last_name: "Doe",
		email: "john@dcism.com",
		role: "ADMIN",
		department: "DCISM",
		course: "BS CS",
		created: "Sep 1, 2026",
	},
	{
		id: 2,
		first_name: "Jane",
		last_name: "Smith",
		email: "jane@dcism.com",
		role: "USER",
		department: "DCISM",
		course: "BS IT",
		created: "Sep 5, 2026",
	},
	{
		id: 3,
		first_name: "Mike",
		last_name: "Chen",
		email: "mike@dcism.com",
		role: "USER",
		department: "DCISM",
		course: "BS CS",
		created: "Sep 10, 2026",
	},
	{
		id: 4,
		first_name: "Anna",
		last_name: "Reyes",
		email: "anna@dcism.com",
		role: "USER",
		department: "DCISM",
		course: "BS IM",
		created: "Sep 12, 2026",
	},
	{
		id: 5,
		first_name: "Carlos",
		last_name: "Garcia",
		email: "carlos@dcism.com",
		role: "USER",
		department: "DCISM",
		course: "BS IT",
		created: "Sep 15, 2026",
	},
	{
		id: 6,
		first_name: "Carlos",
		last_name: "Garcia",
		email: "carlos@dcism.com",
		role: "USER",
		department: "DCISM",
		course: "BS IT",
		created: "Sep 15, 2026",
	},
	{
		id: 7,
		first_name: "Carlos",
		last_name: "Garcia",
		email: "carlos@dcism.com",
		role: "USER",
		department: "DCISM",
		course: "BS IT",
		created: "Sep 15, 2026",
	},
	{
		id: 8,
		first_name: "Carlos",
		last_name: "Garcia",
		email: "carlos@dcism.com",
		role: "USER",
		department: "DCISM",
		course: "BS IT",
		created: "Sep 15, 2026",
	},
	{
		id: 9,
		first_name: "Carlos",
		last_name: "Garcia",
		email: "carlos@dcism.com",
		role: "USER",
		department: "DCISM",
		course: "BS IT",
		created: "Sep 15, 2026",
	},
	{
		id: 10,
		first_name: "Carlos",
		last_name: "Garcia",
		email: "carlos@dcism.com",
		role: "USER",
		department: "DCISM",
		course: "BS IT",
		created: "Sep 15, 2026",
	},
	{
		id: 11,
		first_name: "Carlos",
		last_name: "Garcia",
		email: "carlos@dcism.com",
		role: "USER",
		department: "DCISM",
		course: "BS IT",
		created: "Sep 15, 2026",
	},
	{
		id: 12,
		first_name: "Carlos",
		last_name: "Garcia",
		email: "carlos@dcism.com",
		role: "USER",
		department: "DCISM",
		course: "BS IT",
		created: "Sep 15, 2026",
	},
	{
		id: 13,
		first_name: "Carlos",
		last_name: "Garcia",
		email: "carlos@dcism.com",
		role: "USER",
		department: "DCISM",
		course: "BS IT",
		created: "Sep 15, 2026",
	},
	{
		id: 14,
		first_name: "Carlos",
		last_name: "Garcia",
		email: "carlos@dcism.com",
		role: "USER",
		department: "DCISM",
		course: "BS IT",
		created: "Sep 15, 2026",
	},
	{
		id: 15,
		first_name: "Carlos",
		last_name: "Garcia",
		email: "carlos@dcism.com",
		role: "USER",
		department: "DCISM",
		course: "BS IT",
		created: "Sep 15, 2026",
	},
];
